/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2015-01-17 at 23:41:23 UTC 
 * Modify at your own risk.
 */

package com.appspot.gamerspot_0914.feedsAPI;

/**
 * Service definition for FeedsAPI (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FeedsAPIRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class FeedsAPI extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the feedsAPI library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://gamerspot-0914.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "feedsAPI/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public FeedsAPI(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  FeedsAPI(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAll".
   *
   * This request holds the parameters needed by the feedsAPI server.  After setting any optional
   * parameters, call the {@link GetAll#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetAll getAll() throws java.io.IOException {
    GetAll result = new GetAll();
    initialize(result);
    return result;
  }

  public class GetAll extends FeedsAPIRequest<com.appspot.gamerspot_0914.feedsAPI.model.FeedCollection> {

    private static final String REST_PATH = "feedcollection";

    /**
     * Create a request for the method "getAll".
     *
     * This request holds the parameters needed by the the feedsAPI server.  After setting any
     * optional parameters, call the {@link GetAll#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetAll#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAll() {
      super(FeedsAPI.this, "GET", REST_PATH, null, com.appspot.gamerspot_0914.feedsAPI.model.FeedCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAll setAlt(java.lang.String alt) {
      return (GetAll) super.setAlt(alt);
    }

    @Override
    public GetAll setFields(java.lang.String fields) {
      return (GetAll) super.setFields(fields);
    }

    @Override
    public GetAll setKey(java.lang.String key) {
      return (GetAll) super.setKey(key);
    }

    @Override
    public GetAll setOauthToken(java.lang.String oauthToken) {
      return (GetAll) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAll setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAll) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAll setQuotaUser(java.lang.String quotaUser) {
      return (GetAll) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAll setUserIp(java.lang.String userIp) {
      return (GetAll) super.setUserIp(userIp);
    }

    @Override
    public GetAll set(String parameterName, Object value) {
      return (GetAll) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getByService".
   *
   * This request holds the parameters needed by the feedsAPI server.  After setting any optional
   * parameters, call the {@link GetByService#execute()} method to invoke the remote operation.
   *
   * @param serviceName
   * @return the request
   */
  public GetByService getByService(java.lang.String serviceName) throws java.io.IOException {
    GetByService result = new GetByService(serviceName);
    initialize(result);
    return result;
  }

  public class GetByService extends FeedsAPIRequest<com.appspot.gamerspot_0914.feedsAPI.model.FeedCollection> {

    private static final String REST_PATH = "feedcollection/{serviceName}";

    /**
     * Create a request for the method "getByService".
     *
     * This request holds the parameters needed by the the feedsAPI server.  After setting any
     * optional parameters, call the {@link GetByService#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetByService#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param serviceName
     * @since 1.13
     */
    protected GetByService(java.lang.String serviceName) {
      super(FeedsAPI.this, "GET", REST_PATH, null, com.appspot.gamerspot_0914.feedsAPI.model.FeedCollection.class);
      this.serviceName = com.google.api.client.util.Preconditions.checkNotNull(serviceName, "Required parameter serviceName must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetByService setAlt(java.lang.String alt) {
      return (GetByService) super.setAlt(alt);
    }

    @Override
    public GetByService setFields(java.lang.String fields) {
      return (GetByService) super.setFields(fields);
    }

    @Override
    public GetByService setKey(java.lang.String key) {
      return (GetByService) super.setKey(key);
    }

    @Override
    public GetByService setOauthToken(java.lang.String oauthToken) {
      return (GetByService) super.setOauthToken(oauthToken);
    }

    @Override
    public GetByService setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetByService) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetByService setQuotaUser(java.lang.String quotaUser) {
      return (GetByService) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetByService setUserIp(java.lang.String userIp) {
      return (GetByService) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String serviceName;

    /**

     */
    public java.lang.String getServiceName() {
      return serviceName;
    }

    public GetByService setServiceName(java.lang.String serviceName) {
      this.serviceName = serviceName;
      return this;
    }

    @Override
    public GetByService set(String parameterName, Object value) {
      return (GetByService) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link FeedsAPI}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link FeedsAPI}. */
    @Override
    public FeedsAPI build() {
      return new FeedsAPI(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FeedsAPIRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFeedsAPIRequestInitializer(
        FeedsAPIRequestInitializer feedsapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(feedsapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
